# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 11) do

  create_table "balance_sheets", :force => true do |t|
    t.column "company_id",                      :integer,                                :null => false
    t.column "year_ended",                      :date,                                   :null => false
    t.column "shareholders_funds",              :decimal, :precision => 12, :scale => 2
    t.column "equity_capital",                  :decimal, :precision => 12, :scale => 2
    t.column "share_application_money",         :decimal, :precision => 12, :scale => 2
    t.column "preference_capital",              :decimal, :precision => 12, :scale => 2
    t.column "reserves_and_surplus",            :decimal, :precision => 12, :scale => 2
    t.column "loan_funds",                      :decimal, :precision => 12, :scale => 2
    t.column "secured_loans",                   :decimal, :precision => 12, :scale => 2
    t.column "unsecured_loans",                 :decimal, :precision => 12, :scale => 2
    t.column "total_funds",                     :decimal, :precision => 12, :scale => 2
    t.column "fixed_assets",                    :decimal, :precision => 12, :scale => 2
    t.column "net_block",                       :decimal, :precision => 12, :scale => 2
    t.column "gross_block",                     :decimal, :precision => 12, :scale => 2
    t.column "revaluation_reserves",            :decimal, :precision => 12, :scale => 2
    t.column "accumulated_depreciation",        :decimal, :precision => 12, :scale => 2
    t.column "capital_work_in_progress",        :decimal, :precision => 12, :scale => 2
    t.column "investments",                     :decimal, :precision => 12, :scale => 2
    t.column "net_current_assets",              :decimal, :precision => 12, :scale => 2
    t.column "current_assets",                  :decimal, :precision => 12, :scale => 2
    t.column "current_liabilities",             :decimal, :precision => 12, :scale => 2
    t.column "expenses_not_written_off",        :decimal, :precision => 12, :scale => 2
    t.column "unquoted_investments_book_value", :decimal, :precision => 12, :scale => 2
    t.column "quoted_investments_market_value", :decimal, :precision => 12, :scale => 2
    t.column "contingent_liabilities",          :decimal, :precision => 12, :scale => 2
    t.column "no_of_shares",                    :decimal, :precision => 12, :scale => 2
    t.column "face_value",                      :decimal, :precision => 12, :scale => 2
  end

  create_table "companies", :force => true do |t|
    t.column "nse_symbol",                       :string,                 :null => false
    t.column "stockhive_code",                   :string
    t.column "name",                             :string
    t.column "listing_date",                     :date
    t.column "face_value",                       :decimal
    t.column "closing_price",                    :decimal
    t.column "previous_closing_price",           :decimal
    t.column "traded_quantity",                  :integer
    t.column "traded_value",                     :decimal
    t.column "score",                            :integer
    t.column "sector_id",                        :integer
    t.column "sales_growth_rate",                :decimal
    t.column "expenses_growth_rate",             :decimal
    t.column "quarterly_growth_rate",            :decimal
    t.column "eps",                              :decimal
    t.column "pe_ratio",                         :decimal
    t.column "EVtoSales",                        :decimal
    t.column "EVtoEBITDA",                       :decimal
    t.column "ROE",                              :decimal
    t.column "ROCE",                             :decimal
    t.column "DebttoEquity",                     :decimal
    t.column "NCAVPS",                           :decimal
    t.column "quarterly_results_count",          :integer, :default => 0
    t.column "balance_sheets_count",             :integer, :default => 0
    t.column "profit_and_loss_statements_count", :integer, :default => 0
    t.column "price_to_market_value",            :decimal
    t.column "acid_test_ratio",                  :decimal
  end

  create_table "formulas", :force => true do |t|
    t.column "value",           :string
    t.column "weightage",       :integer
    t.column "price_dependent", :boolean
    t.column "type",            :string
    t.column "trend_array",     :string
  end

  create_table "profit_and_loss_statements", :force => true do |t|
    t.column "company_id",                 :integer,                                :null => false
    t.column "year_ended",                 :date,                                   :null => false
    t.column "operating_income",           :decimal, :precision => 12, :scale => 2
    t.column "cost_of_sales",              :decimal, :precision => 12, :scale => 2
    t.column "material_consumed",          :decimal, :precision => 12, :scale => 2
    t.column "manufacturing_expenses",     :decimal, :precision => 12, :scale => 2
    t.column "personnel_expenses",         :decimal, :precision => 12, :scale => 2
    t.column "selling_expenses",           :decimal, :precision => 12, :scale => 2
    t.column "administrative_expenses",    :decimal, :precision => 12, :scale => 2
    t.column "operating_profit",           :decimal, :precision => 12, :scale => 2
    t.column "other_recurring_income",     :decimal, :precision => 12, :scale => 2
    t.column "pbdit",                      :decimal, :precision => 12, :scale => 2
    t.column "financial_expenses",         :decimal, :precision => 12, :scale => 2
    t.column "write_offs",                 :decimal, :precision => 12, :scale => 2
    t.column "pbdt",                       :decimal, :precision => 12, :scale => 2
    t.column "depreciation",               :decimal, :precision => 12, :scale => 2
    t.column "pbt",                        :decimal, :precision => 12, :scale => 2
    t.column "tax",                        :decimal, :precision => 12, :scale => 2
    t.column "pat",                        :decimal, :precision => 12, :scale => 2
    t.column "non_recurring_items",        :decimal, :precision => 12, :scale => 2
    t.column "other_non_cash_adjustments", :decimal, :precision => 12, :scale => 2
    t.column "net_profit",                 :decimal, :precision => 12, :scale => 2
    t.column "equity_dividend",            :decimal, :precision => 12, :scale => 2
    t.column "preference_dividend",        :decimal, :precision => 12, :scale => 2
    t.column "adjusted_eps",               :decimal, :precision => 12, :scale => 2
    t.column "reported_eps",               :decimal, :precision => 12, :scale => 2
    t.column "no_of_shares",               :decimal, :precision => 12, :scale => 2
    t.column "face_value",                 :decimal, :precision => 5,  :scale => 2
  end

  create_table "quarterly_results", :force => true do |t|
    t.column "company_id",             :integer,                                :null => false
    t.column "quarter_ended",          :date,                                   :null => false
    t.column "total_income",           :decimal, :precision => 12, :scale => 2
    t.column "net_sales",              :decimal, :precision => 12, :scale => 2
    t.column "sales",                  :decimal, :precision => 12, :scale => 2
    t.column "excise",                 :decimal, :precision => 12, :scale => 2
    t.column "other_income",           :decimal, :precision => 12, :scale => 2
    t.column "total_expenses",         :decimal, :precision => 12, :scale => 2
    t.column "stock_adjustment",       :decimal, :precision => 12, :scale => 2
    t.column "raw_materials",          :decimal, :precision => 12, :scale => 2
    t.column "employee_expenses",      :decimal, :precision => 12, :scale => 2
    t.column "other_expenses",         :decimal, :precision => 12, :scale => 2
    t.column "pbdit",                  :decimal, :precision => 12, :scale => 2
    t.column "interest",               :decimal, :precision => 12, :scale => 2
    t.column "pbdt",                   :decimal, :precision => 12, :scale => 2
    t.column "depreciation",           :decimal, :precision => 12, :scale => 2
    t.column "pbt",                    :decimal, :precision => 12, :scale => 2
    t.column "tax",                    :decimal, :precision => 12, :scale => 2
    t.column "extraordinary_item",     :decimal, :precision => 12, :scale => 2
    t.column "net_profit",             :decimal, :precision => 12, :scale => 2
    t.column "eps",                    :decimal, :precision => 12, :scale => 2
    t.column "equity_capital",         :decimal, :precision => 12, :scale => 2
    t.column "face_value",             :decimal, :precision => 8,  :scale => 3
    t.column "no_of_shares",           :decimal, :precision => 8,  :scale => 2
    t.column "public_shareholding",    :decimal, :precision => 5,  :scale => 2
    t.column "type",                   :string
    t.column "total_interest",         :decimal, :precision => 12, :scale => 2
    t.column "government_share",       :decimal, :precision => 5,  :scale => 2
    t.column "capital_adequacy_ratio", :decimal, :precision => 5,  :scale => 2
  end

  create_table "sectors", :force => true do |t|
    t.column "name",                  :string,  :limit => nil,                                :default => ""
    t.column "eps",                   :decimal,                :precision => 12, :scale => 2, :default => 0.0
    t.column "pe_ratio",              :decimal,                :precision => 12, :scale => 2, :default => 0.0
    t.column "EVtoSales",             :decimal,                                               :default => 0.0
    t.column "EVtoEBITDA",            :decimal,                                               :default => 0.0
    t.column "ROE",                   :decimal,                                               :default => 0.0
    t.column "ROCE",                  :decimal,                                               :default => 0.0
    t.column "DebttoEquity",          :decimal,                                               :default => 0.0
    t.column "NCAVPS",                :decimal,                                               :default => 0.0
    t.column "price_to_book_value",   :decimal
    t.column "price_to_market_value", :decimal
    t.column "companies_count",       :integer,                                               :default => 0
  end

end
